feat: setup ci
SuteraVR/VanillaClocker pull request #7
Opened 2024-09-01 08:25 UTC by HMasataka

2024-09-14 10:47 UTC, AsPulse requested changes
- どれでチェックが落ちたのか分かりづらいのでワークフロー分けてほしいです！
-`shell: bash`不要ですが一応付けてる感じですか……？
- toolchainなんですけど、`rust-toolchain.toml`を見るはずなので不要です

2024-09-14 10:59 UTC, HMasataka commented
直します！

> shell: bash不要ですが一応付けてる感じですか……？

GitHub Actionsだとshell指定するかbash指定するかで内部で実行されるコマンドが違ってて指定した方が良いケース多いみたいだから一応付けてましたー
今回はそれほど重要でもないので消しても良いかも
https://docs.github.com/ja/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell)

2024-09-15 01:00 UTC, HMasataka commented
ひとまず指摘部分消してワークフロー組み直しました

2024-09-15 03:16 UTC, AsPulse approved these changes
LGTM!!!

2024-09-16 01:29 UTC, merged