thiserror, tracingクレートの導入
SuteraVR/VanillaClocker pull request #8
Opened 2024-10-04 12:54 UTC by HMasataka

2024-10-22 13:13 UTC, AsPulse requested changes

2024-10-22 13:13 UTC, AsPulse commented on clocking-server/src/err.rs
> +    ConvertBuffer(FromUtf8Error),
ぜ、全体的にエラー文が雑……！
「ReadFile」や「OpenFile」とかのエラーはよくないです
代わりに、`LoadPrivateKeyFile`みたいな……意識する場所としては、「それを受けとったユーザーが何をすればいいのか」が分かるように……！
逆にそのようにエラーがまとまってれば、Openで失敗したかReadで失敗したかは割とどうでもいいわけです。
(きっと {0} のように参照される部分で表示されるからね！例えば`Failed to load Private Key File: file not found` みたいな)

また、エラー文の末尾にピリオドとかはつけません 

いろいろ参考になるかも？
https://doc.rust-jp.rs/rust-by-example-ja/error/multiple_error_types/define_error_type.html

2024-10-24 03:42 UTC, AsPulse commented
あと、プルリクエスト名がメインブランチへのコミットメッセージになっちゃうのでConventionalに従ってください

2025-01-09 04:34 UTC, HMasataka commented
@AsPulse 
めっちゃ遅くなっちゃったけど更新したのでお手隙で見てくださいー！
79fc9dd5176df8ef85314c92181842111b2de64f

2025-01-09 07:00 UTC, AsPulse approved these changes
LGTM! + 1つ別のIssueに回します（レビュー参照）

2025-01-09 07:00 UTC, AsPulse commented on clocking-server/src/main.rs
> +            .map_err(ClockerError::AcceptNewConnection)?;
このエラーがどんな時に発生するのかわからないんだけど、ここで `?` を使うとプログラムがそのまま終了してしまうから、もし接続のタイムアウトとか外的要因でエラーが発生する可能性があるなら、こうするべきではないかもね

ただ、エラーログを正しく出力する仕組みを教えてないし、別に開発段階では外的要因で終了しても困らないから、別Issueとして建ててあとで対処しましょう

2025-01-09 09:03 UTC, HMasataka commented on clocking-server/src/main.rs
> +            .map_err(ClockerError::AcceptNewConnection)?;
なるほど確かに
僕も別途対応で問題ないとは思うのでひとまずこのPRはマージしちゃいます

2025-01-09 09:04 UTC, merged